// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 16.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PentaWork.Xrm.PowerShell.XrmProxies.Templates.CSharp
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Microsoft.Xrm.Sdk.Metadata;
    using PentaWork.Xrm.PowerShell.XrmProxies.Model;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Fake : FakeBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Bogus;\r\nusing System;\r\nusing FakeXrmEasy;\r\nusing System.Collections.Generic" +
                    ";\r\nusing ");
            
            #line 12 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProxyNamespace));
            
            #line default
            #line hidden
            this.Write(".Entities;\r\n\r\nnamespace ");
            
            #line 14 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FakeNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic static class Fake");
            
            #line 16 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityInfo.UniqueDisplayName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\t\r\n\t\t#region FakeRelationships\r\n\t\tpublic static class Relationships \r\n\t\t{\r\n");
            
            #line 21 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
		foreach(var relation in EntityInfo.OneToManyRelationList){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t/// <summary>1:N ");
            
            #line 22 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.SchemaName));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t\t\tpublic static readonly XrmFakedRelationship ");
            
            #line 23 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.UniqueDisplayName));
            
            #line default
            #line hidden
            this.Write(" = \r\n\t\t\t\tnew XrmFakedRelationship\r\n\t\t\t\t{\r\n\t\t\t\t\tEntity1Attribute = \"");
            
            #line 26 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityInfo.PrimaryIdAttribute.LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity2Attribute = \"");
            
            #line 27 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.RelatedEntityAttributeName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity1LogicalName = \"");
            
            #line 28 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityInfo.LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity2LogicalName = \"");
            
            #line 29 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.RelatedEntityInfo.LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tRelationshipType = XrmFakedRelationship.enmFakeRelationshipType.OneToMan" +
                    "y\r\n\t\t\t\t};\r\n\r\n");
            
            #line 33 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
		} 
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
		foreach(var relation in EntityInfo.ManyToManyRelationList){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t/// <summary>N:N ");
            
            #line 35 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.SchemaName));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t\t\tpublic static readonly XrmFakedRelationship ");
            
            #line 36 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.UniqueDisplayName));
            
            #line default
            #line hidden
            this.Write(" = \r\n\t\t\t\tnew XrmFakedRelationship\r\n\t\t\t\t{\r\n\t\t\t\t\tIntersectEntity = \"");
            
            #line 39 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.SchemaName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity1Attribute = \"");
            
            #line 40 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Entity1Attribute));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity2Attribute = \"");
            
            #line 41 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Entity2Attribute));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity1LogicalName = \"");
            
            #line 42 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Entity1LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tEntity2LogicalName = \"");
            
            #line 43 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.Entity2LogicalName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\tRelationshipType = XrmFakedRelationship.enmFakeRelationshipType.ManyToMa" +
                    "ny\r\n\t\t\t\t};\r\n\r\n");
            
            #line 47 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t\t#endregion\r\n\r\n\t\t#region Fake\r\n\t\tpublic static ");
            
            #line 52 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityInfo.UniqueDisplayName));
            
            #line default
            #line hidden
            this.Write(" Create()\r\n\t\t{\r\n");
            
            #line 54 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
		var rules = new List<string>();
		foreach(var attribute in EntityInfo.AttributeList)
		{
			var attType = attribute.AttributeType;
            switch (attType)
            { 				
				case AttributeTypeCode.Double:
					rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.Random.Double())");
                    break;
				case AttributeTypeCode.Decimal:
				case AttributeTypeCode.Money:
					rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.Finance.Amount())");
                    break;
                case AttributeTypeCode.Picklist:
				case AttributeTypeCode.Status:
				case AttributeTypeCode.State:
					rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.PickRandom<{EntityInfo.UniqueDisplayName}.{attribute.ReturnType}>())");
                    break;
				case AttributeTypeCode.Virtual:
					if(attribute.AttributeMetadata is MultiSelectPicklistAttributeMetadata multiSelect)
					{
						rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => new List<{EntityInfo.UniqueDisplayName}.{attribute.ReturnType}> {{ fake.PickRandom<{EntityInfo.UniqueDisplayName}.{attribute.ReturnType}>() }})");
					}
					break;
				case AttributeTypeCode.Integer:
                case AttributeTypeCode.BigInt:
					rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.Random.Int())");
					break;
				case AttributeTypeCode.Uniqueidentifier:
					rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => Guid.NewGuid())");
					break;
				case AttributeTypeCode.Memo:
                case AttributeTypeCode.String:
                case AttributeTypeCode.EntityName:
					rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.Lorem.Word())");
					break;
				case AttributeTypeCode.Boolean:
                    rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.Random.Bool())");
                    break;
                case AttributeTypeCode.DateTime:
                    rules.Add($".RuleFor(e => e.{attribute.UniqueDisplayName}, fake => fake.Date.Soon())");
                    break;
            }
		}
            
            #line default
            #line hidden
            this.Write("\t\t\tvar faker = new Faker<");
            
            #line 98 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityInfo.UniqueDisplayName));
            
            #line default
            #line hidden
            this.Write(">()\r\n\t\t\t");
            
            #line 99 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join($"{Environment.NewLine}\t\t\t", rules.ToArray())));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\treturn faker.Generate();\r\n\t\t}\r\n\t\t#endregion\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 106 "C:\Users\GerritGazic\source\repos\PentaWork.Xrm.PowerShell\src\PentaWork.Xrm.PowerShell\XrmProxies\Templates\CSharp\Fake.tt"

public EntityInfo EntityInfo { get; set; }
public string ProxyNamespace { get; set; }
public string FakeNamespace { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class FakeBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
